import {
  Merchant,
  DashboardData,
  ProductPerformance,
  InventoryRisk,
  CustomerMetrics,
  AtRiskCustomer,
  Promotion,
  Campaign,
  ChatResponse,
  HealthStatus,
} from "@/types";

export const MOCK_MERCHANT: Merchant = {
  id: 1,
  name: "Rajesh Kumar",
  email: "rajesh.fastfood@paytm-merchant.com",
  phone: "+91 98765 43210",
  business_name: "Rajesh Fast Food & Cafe",
  business_type: "Quick Service Restaurant",
  created_at: "2023-01-15T08:30:00Z",
};

export const MOCK_DASHBOARD: DashboardData = {
  merchant_id: 1,
  sales_summary: {
    today_sales: 1850,
    today_orders: 12,
    monthly_sales: 48250,
    monthly_orders: 310,
    previous_monthly_sales: 64800,
    sales_growth_percent: -25.54,
    average_order_value: 155.65,
  },
  top_selling_products: [
    {
      product_id: 101,
      name: "Veg Pizza 8-inch",
      category: "Pizza",
      price: 220,
      current_sales: 21780,
      previous_sales: 18500,
      growth_percent: 17.73,
      quantity_sold: 99,
    },
    {
      product_id: 102,
      name: "Masala Dosa",
      category: "South Indian",
      price: 110,
      current_sales: 14300,
      previous_sales: 13200,
      growth_percent: 8.33,
      quantity_sold: 130,
    },
    {
      product_id: 103,
      name: "Chocolate Shake",
      category: "Beverages",
      price: 140,
      current_sales: 11200,
      previous_sales: 10500,
      growth_percent: 6.67,
      quantity_sold: 80,
    },
    {
      product_id: 104,
      name: "Cold Coffee",
      category: "Beverages",
      price: 80,
      current_sales: 8800,
      previous_sales: 12220,
      growth_percent: -28.0,
      quantity_sold: 110,
    },
    {
      product_id: 105,
      name: "French Fries",
      category: "Sides",
      price: 90,
      current_sales: 7200,
      previous_sales: 7000,
      growth_percent: 2.86,
      quantity_sold: 80,
    },
  ],
  declining_products: [
    {
      product_id: 201,
      name: "Veg Supreme Burger",
      category: "Burgers",
      price: 120,
      current_sales: 7560,
      previous_sales: 11460,
      growth_percent: -34.03,
      quantity_sold: 63,
    },
    {
      product_id: 202,
      name: "Paneer Roll",
      category: "Rolls",
      price: 110,
      current_sales: 2970,
      previous_sales: 3960,
      growth_percent: -25.0,
      quantity_sold: 27,
    },
    {
      product_id: 104,
      name: "Cold Coffee",
      category: "Beverages",
      price: 80,
      current_sales: 8800,
      previous_sales: 12220,
      growth_percent: -28.0,
      quantity_sold: 110,
    },
  ],
  inventory_risk: {
    low_stock_count: 1,
    excess_stock_count: 1,
    stockout_risk_count: 1,
    items: [
      {
        id: 1,
        product_id: 201,
        product_name: "Veg Supreme Burger (Buns)",
        category: "Bakery",
        current_stock: 8,
        min_reorder_level: 15,
        max_stock_level: 50,
        status: "Low Stock",
        recommended_reorder_qty: 42,
        stockout_risk: "High",
      },
      {
        id: 2,
        product_id: 104,
        product_name: "Cold Coffee (Beans & Decoction)",
        category: "Beverages",
        current_stock: 180,
        min_reorder_level: 20,
        max_stock_level: 50,
        status: "Excess Stock",
        recommended_reorder_qty: 0,
        stockout_risk: "Low",
      },
      {
        id: 3,
        product_id: 101,
        product_name: "Pizza Base 8-inch",
        category: "Bakery",
        current_stock: 52,
        min_reorder_level: 20,
        max_stock_level: 60,
        status: "Healthy",
        recommended_reorder_qty: 0,
        stockout_risk: "Low",
      },
    ],
  },
  customer_metrics: {
    total_customers: 60,
    new_customers: 4,
    returning_customers: 36,
    repeat_purchase_rate: 60.0,
    inactive_customers_count: 24,
    at_risk_customers_count: 5,
  },
  alerts_and_opportunities: [
    {
      type: "warning",
      title: "Sales Decline Detected",
      message: "Monthly sales are down by 25.54% compared to last month.",
    },
    {
      type: "warning",
      title: "Declining Product",
      message: "Veg Supreme Burger sales dropped by 34.03%.",
    },
    {
      type: "opportunity",
      title: "Excess Inventory Opportunity",
      message: "Excess stock detected in Cold Coffee (180 units vs 50 max level).",
    },
    {
      type: "opportunity",
      title: "Customer Re-engagement",
      message: "You have 24 inactive customers who haven't ordered in over 30 days.",
    },
  ],
};

export const MOCK_AT_RISK_CUSTOMERS: AtRiskCustomer[] = [
  {
    id: 1001,
    name: "Customer #1001",
    phone: "+91 98*** **123",
    email: "customer1***@gmail.com",
    last_order_date: "2026-07-14",
    days_inactive: 66,
    total_orders: 6,
    total_spend: 1450,
  },
  {
    id: 1002,
    name: "Customer #1002",
    phone: "+91 98*** **456",
    email: "customer2***@gmail.com",
    last_order_date: "2026-07-20",
    days_inactive: 60,
    total_orders: 4,
    total_spend: 920,
  },
  {
    id: 1003,
    name: "Customer #1003",
    phone: "+91 97*** **789",
    email: "customer3***@gmail.com",
    last_order_date: "2026-07-28",
    days_inactive: 52,
    total_orders: 8,
    total_spend: 2100,
  },
  {
    id: 1004,
    name: "Customer #1004",
    phone: "+91 96*** **321",
    email: "customer4***@gmail.com",
    last_order_date: "2026-08-04",
    days_inactive: 45,
    total_orders: 3,
    total_spend: 680,
  },
  {
    id: 1005,
    name: "Customer #1005",
    phone: "+91 99*** **654",
    email: "customer5***@gmail.com",
    last_order_date: "2026-08-10",
    days_inactive: 39,
    total_orders: 5,
    total_spend: 1150,
  },
];

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: 301,
    merchant_id: 1,
    name: "Monsoon Special 15% Off",
    discount_percent: 15,
    discount_amount: 0,
    start_date: "2026-08-01",
    end_date: "2026-08-31",
    target_category: "Burgers",
    status: "Completed",
    actual_sales: 13500,
    incremental_sales: 2025,
    roi_percent: 0,
    effectiveness: "ineffective",
  },
  {
    id: 302,
    merchant_id: 1,
    name: "Weekend Pizza Feast Combo",
    discount_percent: 20,
    discount_amount: 0,
    start_date: "2026-09-01",
    end_date: "2026-09-15",
    target_category: "Pizza",
    status: "Active",
    actual_sales: 21780,
    incremental_sales: 5400,
    roi_percent: 34.5,
    effectiveness: "high",
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 501,
    merchant_id: 1,
    title: "Burger + Cold Coffee Combo Campaign",
    description: "Suggesting a special combo of Veg Supreme Burger (₹120) + Cold Coffee (₹80) bundled at ₹149. Solves excess coffee stock and revives burger sales.",
    campaign_type: "combo_offer",
    target_audience: "24 inactive customers & walk-in Paytm App users",
    status: "pending_approval",
    metrics_json: {
      regular_price: 200,
      suggested_price: 149,
      expected_conversion_increase: "18%",
      estimated_revenue_boost: "₹6,800/month",
      recommended_items: ["Veg Supreme Burger", "Cold Coffee"],
    },
    created_at: "2026-09-18T10:00:00Z",
    updated_at: "2026-09-18T10:00:00Z",
  },
  {
    id: 502,
    merchant_id: 1,
    title: "Winback SMS & App Push for 24 Inactive Customers",
    description: "Targeted ₹50 cashback coupon on Paytm QR payments for customers inactive for 30+ days.",
    campaign_type: "winback_coupon",
    target_audience: "24 inactive customers",
    status: "active",
    metrics_json: {
      coupon_code: "WELCOME50",
      redemption_rate: "12.5%",
      actual_conversions: 3,
    },
    created_at: "2026-09-10T14:30:00Z",
    updated_at: "2026-09-12T09:15:00Z",
  },
];

export const MOCK_CHAT_RESPONSES: Record<string, ChatResponse> = {
  default: {
    message: "Aapki sales is month 25.54% down hai. Base analysis se pata chala hai ki Veg Supreme Burger ki demand 34.03% giri hai aur Cold Coffee ka stock excess (180 units) ho chuka hai. Isko resolve karne ke liye humne ek high-margin Burger + Cold Coffee Combo ₹149 mein design kiya hai.",
    language: "hinglish",
    workers: [
      "Sales Worker",
      "Product Worker",
      "Customer Worker",
      "Promotion Worker",
      "Forecast Worker",
    ],
    suggestions: [
      "Which products are declining?",
      "What should I restock?",
      "Suggest a winback promotion for 24 inactive customers",
    ],
    visuals: [
      {
        type: "line_chart",
        data_source: "sales_trend",
        payload: {
          title: "Sales Growth Trend (Last 6 Months)",
          series: [
            { period: "Mar", sales: 2417 },
            { period: "Apr", sales: 3027 },
            { period: "May", sales: 3088 },
            { period: "Jun", sales: 4883 },
            { period: "Jul", sales: 4689 },
            { period: "Aug", sales: 3134 },
            { period: "Sep", sales: 1417 },
          ],
        },
      },
      {
        type: "bar_chart",
        data_source: "declining_products",
        payload: {
          title: "Top Products Losing Demand",
          items: [
            { name: "Veg Supreme Burger", drop: -34.03, sales: 7560 },
            { name: "Cold Coffee", drop: -28.0, sales: 8800 },
            { name: "Paneer Roll", drop: -25.0, sales: 2970 },
          ],
        },
      },
    ],
  },
};

export const MOCK_HEALTH: HealthStatus = {
  status: "ok",
  services: {
    api: "healthy",
    database: "healthy",
    n8n: "available",
    ml_service: "available",
  },
};
